=== tunikakeks/PowerNukkit/src/test/resources/cn/nukkit/item/basicAttributes.dtd
<!ELEMENT minecraft-attributes (items)>

<!ELEMENT items (item*)>

<!ELEMENT item (item-state*)>
        <!ATTLIST item
                namespaced-id ID #REQUIRED
                numeric-id CDATA #REQUIRED
                name CDATA #REQUIRED
                stack-size CDATA "64"
                durability CDATA #IMPLIED
                fuel-time CDATA #IMPLIED
                tool (true|false) #IMPLIED
                tier (none|leather|chain|other|wood|gold|stone|iron|diamond|netherite) "none"
                axe (true|false) "false"
                pickaxe (true|false) "false"
                shovel (true|false) "false"
                hoe (true|false) "false"
                sword (true|false) "false"
                shears (true|false) "false"
                armor (true|false) #IMPLIED
                helmet (true|false) "false"
                chestplate (true|false) "false"
                leggings (true|false) "false"
                boots (true|false) "false"
                enchantability CDATA #IMPLIED
                attack-damage CDATA "1"
                armor-points CDATA "0"
                toughness CDATA "0"
                unbreakable (true|false) "false"
                lava-resistant (true|false) "false"
                fertilizer (true|false) "false"
                food CDATA ""
                saturation CDATA ""
        >

<!ELEMENT item-state EMPTY>
        <!ATTLIST item-state
                namespaced-id ID #IMPLIED
                numeric-id CDATA #IMPLIED
                damage CDATA #REQUIRED
                name CDATA #IMPLIED
                stack-size CDATA #IMPLIED
                durability CDATA #IMPLIED
                fuel-time CDATA #IMPLIED
                tool (true|false) #IMPLIED
                tier (wooden|leather|gold|stone|iron|diamond|netherite) #IMPLIED
                axe (true|false) #IMPLIED
                pickaxe (true|false) #IMPLIED
                shovel (true|false) #IMPLIED
                hoe (true|false) #IMPLIED
                sword (true|false) #IMPLIED
                shears (true|false) #IMPLIED
                armor (true|false) #IMPLIED
                helmet (true|false) #IMPLIED
                chestplate (true|false) #IMPLIED
                leggings (true|false) #IMPLIED
                boots (true|false) #IMPLIED
                enchantability CDATA #IMPLIED
                attack-damage CDATA #IMPLIED
                armor-points CDATA #IMPLIED
                toughness CDATA #IMPLIED
                unbreakable (true|false) #IMPLIED
                lava-resistant (true|false) #IMPLIED
                fertilizer (true|false) #IMPLIED
        >

=== tunikakeks/PowerNukkit/src/test/resources/cn/nukkit/item/basicItemAttributes.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE items SYSTEM "basicAttributes.dtd">
<items>
    <item namespaced-id="minecraft:iron_shovel" numeric-id="256" name="Iron Shovel" tool="true" shovel="true" tier="iron" durability="251" stack-size="1" />
    <item namespaced-id="minecraft:iron_pickaxe" numeric-id="257" name="Iron Pickaxe" tool="true" pickaxe="true" tier="iron" durability="251" stack-size="1"/>
    <item namespaced-id="minecraft:iron_axe" numeric-id="258" name="Iron Axe" tool="true" axe="true" tier="iron" durability="251" stack-size="1"/>
    <item namespaced-id="minecraft:flint_and_steel" numeric-id="259" name="Flint and Steel" tool="true" stack-size="1" durability="65"/>
    <item namespaced-id="minecraft:apple" numeric-id="260" name="Apple" food="4" saturation="2.4"/>
    <item namespaced-id="minecraft:bow" numeric-id="261" name="Bow" tool="true" stack-size="1" durability="385" enchantability="1" fuel-time="200"/>
    <item namespaced-id="minecraft:arrow" numeric-id="262" name="Arrow">
        <item-state damage="1" name="Arrow of Splashing" />
        <item-state damage="2" name="Tipped Arrow" />
        <item-state damage="3" name="Tipped Arrow" />
        <item-state damage="4" name="Tipped Arrow" />
        <item-state damage="5" name="Tipped Arrow" />
        <item-state damage="6" name="Arrow of Night Vision" />
        <item-state damage="7" name="Arrow of Night Vision" />
        <item-state damage="8" name="Arrow of Invisibility" />
        <item-state damage="9" name="Arrow of Invisibility" />
        <item-state damage="10" name="Arrow of Leaping" />
        <item-state damage="11" name="Arrow of Leaping" />
        <item-state damage="12" name="Arrow of Leaping" />
        <item-state damage="13" name="Arrow of Fire Resistance" />
        <item-state damage="14" name="Arrow of Fire Resistance" />
        <item-state damage="15" name="Arrow of Swiftness" />
        <item-state damage="16" name="Arrow of Swiftness" />
        <item-state damage="17" name="Arrow of Swiftness" />
        <item-state damage="18" name="Arrow of Slowness" />
        <item-state damage="19" name="Arrow of Slowness" />
        <item-state damage="43" name="Arrow of Slowness" />
        <item-state damage="20" name="Arrow of Water Breathing" />
        <item-state damage="21" name="Arrow of Water Breathing" />
        <item-state damage="22" name="Arrow of Healing" />
        <item-state damage="23" name="Arrow of Healing" />
        <item-state damage="24" name="Arrow of Harming" />
        <item-state damage="25" name="Arrow of Harming" />
        <item-state damage="26" name="Arrow of Poison" />
        <item-state damage="27" name="Arrow of Poison" />
        <item-state damage="28" name="Arrow of Poison" />
        <item-state damage="29" name="Arrow of Regeneration" />
        <item-state damage="30" name="Arrow of Regeneration" />
        <item-state damage="31" name="Arrow of Regeneration" />
        <item-state damage="32" name="Arrow of Strength" />
        <item-state damage="33" name="Arrow of Strength" />
        <item-state damage="34" name="Arrow of Strength" />
        <item-state damage="35" name="Arrow of Weakness" />
        <item-state damage="36" name="Arrow of Weakness" />
        <item-state damage="37" name="Arrow of Decay" />
        <item-state damage="38" name="Arrow of the Turtle Master" />
        <item-state damage="39" name="Arrow of the Turtle Master" />
        <item-state damage="40" name="Arrow of the Turtle Master" />
        <item-state damage="41" name="Arrow of Slow Falling" />
        <item-state damage="42" name="Arrow of Slow Falling" />
    </item>
    <item namespaced-id="minecraft:coal" numeric-id="263" name="Coal" fuel-time="1600">
        <item-state namespaced-id="minecraft:charcoal" damage="1" name="Charcoal"/>
    </item>
    <item namespaced-id="minecraft:diamond" numeric-id="264" name="Diamond"/>
    <item namespaced-id="minecraft:iron_ingot" numeric-id="265" name="Iron Ingot"/>
    <item namespaced-id="minecraft:gold_ingot" numeric-id="266" name="Gold Ingot"/>
    <item namespaced-id="minecraft:iron_sword" numeric-id="267"  name="Iron Sword" tool="true" sword="true" tier="iron" durability="251" stack-size="1"/>
    <item namespaced-id="minecraft:wooden_sword" numeric-id="268" name="Wooden Sword" tool="true" sword="true" tier="wood" durability="60" stack-size="1"  fuel-time="200"/>
    <item namespaced-id="minecraft:wooden_shovel" numeric-id="269" name="Wooden Shovel" tool="true" shovel="true" tier="wood" durability="60" stack-size="1" fuel-time="200"/>
    <item namespaced-id="minecraft:wooden_pickaxe" numeric-id="270" name="Wooden Pickaxe" tool="true" pickaxe="true" tier="wood" durability="60" stack-size="1" fuel-time="200"/>
    <item namespaced-id="minecraft:wooden_axe" numeric-id="271" name="Wooden Axe" tool="true" axe="true" tier="wood" durability="60" stack-size="1" fuel-time="200"/>
    <item namespaced-id="minecraft:stone_sword" numeric-id="272" name="Stone Sword" tool="true" sword="true" tier="stone" durability="132" stack-size="1"/>
    <item namespaced-id="minecraft:stone_shovel" numeric-id="273" name="Stone Shovel" tool="true" shovel="true" tier="stone" durability="132" stack-size="1"/>
    <item namespaced-id="minecraft:stone_pickaxe" numeric-id="274" name="Stone Pickaxe" tool="true" pickaxe="true" tier="stone" durability="132" stack-size="1"/>
    <item namespaced-id="minecraft:stone_axe" numeric-id="275" name="Stone Axe" tool="true" axe="true" tier="stone" durability="132" stack-size="1"/>
    <item namespaced-id="minecraft:diamond_sword" numeric-id="276" name="Diamond Sword" tool="true" sword="true" tier="diamond" durability="1562" stack-size="1"/>
    <item namespaced-id="minecraft:diamond_shovel" numeric-id="277" name="Diamond Shovel" tool="true" shovel="true" tier="diamond" durability="1562" stack-size="1"/>
    <item namespaced-id="minecraft:diamond_pickaxe" numeric-id="278" name="Diamond Pickaxe" tool="true" pickaxe="true" tier="diamond" durability="1562" stack-size="1"/>
    <item namespaced-id="minecraft:diamond_axe" numeric-id="279" name="Diamond Axe" tool="true" axe="true" tier="diamond" durability="1562" stack-size="1"/>
    <item namespaced-id="minecraft:stick" numeric-id="280" name="Stick" fuel-time="100"/>
    <item namespaced-id="minecraft:bowl" numeric-id="281" name="Bowl" fuel-time="100"/>
    <item namespaced-id="minecraft:mushroom_stew" numeric-id="282" name="Mushroom Stew" stack-size="1"/>
    <item namespaced-id="minecraft:golden_sword" numeric-id="283" name="Golden Sword" tool="true" sword="true" tier="gold" durability="33" stack-size="1"/>
    <item namespaced-id="minecraft:golden_shovel" numeric-id="284" name="Golden Shovel" tool="true" shovel="true" tier="gold" durability="33" stack-size="1"/>
    <item namespaced-id="minecraft:golden_pickaxe" numeric-id="285" name="Golden Pickaxe" tool="true" pickaxe="true" tier="gold" durability="33" stack-size="1"/>
    <item namespaced-id="minecraft:golden_axe" numeric-id="286" name="Golden Axe" tool="true" axe="true" tier="gold" durability="33" stack-size="1"/>
    <item namespaced-id="minecraft:string" numeric-id="287" name="String"/>
    <item namespaced-id="minecraft:feather" numeric-id="288" name="Feather"/>
    <item namespaced-id="minecraft:gunpowder" numeric-id="289" name="Gunpowder"/>
    <item namespaced-id="minecraft:wooden_hoe" numeric-id="290" name="Wooden Hoe" tool="true" hoe="true" tier="wood" durability="60" stack-size="1" fuel-time="200"/>
    <item namespaced-id="minecraft:stone_hoe" numeric-id="291" name="Stone Hoe" tool="true" hoe="true" tier="stone" durability="132" stack-size="1"/>
    <item namespaced-id="minecraft:iron_hoe" numeric-id="292" name="Iron Hoe" tool="true" hoe="true" tier="iron" durability="251" stack-size="1"/>
    <item namespaced-id="minecraft:diamond_hoe" numeric-id="293" name="Diamond Hoe" tool="true" hoe="true" tier="diamond" durability="1562" stack-size="1"/>
    <item namespaced-id="minecraft:golden_hoe" numeric-id="294" name="Golden Hoe" tool="true" hoe="true" tier="gold" durability="33" stack-size="1"/>
    <item namespaced-id="minecraft:wheat_seeds" numeric-id="295" name="Wheat Seeds"/>
    <item namespaced-id="minecraft:wheat" numeric-id="296" name="Wheat"/>
    <item namespaced-id="minecraft:bread" numeric-id="297" name="Bread"/>
    <item namespaced-id="minecraft:leather_helmet" numeric-id="298" name="Leather Cap" armor="true" tier="leather" helmet="true" durability="56" stack-size="1" />
    <item namespaced-id="minecraft:leather_chestplate" numeric-id="299" name="Leather Tunic" armor="true" durability="81" tier="leather" chestplate="true" stack-size="1"/>
    <item namespaced-id="minecraft:leather_leggings" numeric-id="300" name="Leather Pants" armor="true" tier="leather" leggings="true" stack-size="1" durability="76"/>
    <item namespaced-id="minecraft:leather_boots" numeric-id="301" name="Leather Boots" armor="true" boots="true" tier="leather" stack-size="1" durability="66"/>
    <item namespaced-id="minecraft:chainmail_helmet" numeric-id="302" name="Chainmail Helmet" armor="true" helmet="true" tier="chain" durability="166" stack-size="1"/>
    <item namespaced-id="minecraft:chainmail_chestplate" numeric-id="303" name="Chainmail Chestplate" armor="true" chestplate="true" tier="chain" durability="241" stack-size="1"/>
    <item namespaced-id="minecraft:chainmail_leggings" numeric-id="304" name="Chainmail Leggings" armor="true" tier="chain" leggings="true" stack-size="1" durability="226"/>
    <item namespaced-id="minecraft:chainmail_boots" numeric-id="305" name="Chainmail Boots" armor="true" tier="chain" boots="true" stack-size="1" durability="196"/>
    <item namespaced-id="minecraft:iron_helmet" numeric-id="306" name="Iron Helmet" armor="true" tier="iron" durability="166" stack-size="1" helmet="true"/>
